GuardarSessionObjetos/Models/ErrorViewModel.cs
namespace GuardarSessionObjetos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuardarSessionObjetos/Models/Usuario.cs
namespace GuardarSessionObjetos.Models
{
    public class Usuario
    {
            public string Nombre { get; set; }
            public string Email { get; set; }
            public int Edad { get; set; }
            public string Ciudad { get; set; }
    }
}

GuardarSessionObjetos/Controllers/HomeController.cs
using GuardarSessionObjetos.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GuardarSessionObjetos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuardarSessionObjetos/Controllers/SessionController.cs
using GuardarSessionObjetos.Extensions;
using GuardarSessionObjetos.Models;
using Microsoft.AspNetCore.Mvc;

namespace GuardarSessionObjetos.Controllers
{
    public class SessionController : Controller
    {
        public IActionResult GuardarObjetoSession(int? btnpulsado)
        {
            if(btnpulsado != null)
            {
                if(btnpulsado.Value == 1)
                {
                    //CREAMOS EL OBJETO USUARIO QUE QUEREMOS GUARDAR EN SESSION
                    Usuario user = new Usuario();
                    user.Nombre = "Usuario";
                    user.Email = "usuario@gmail.com";
                    user.Edad = 20;
                    user.Ciudad = "Madrid";
                    //ALMACENAMOS EN SESSION EL OBJETO COCHE UTILIZANDO LOS DOS NUEVOS METODOS
                    HttpContext.Session.SetObject("usuario", user);
                    ViewData["mensaje"] = "Se ha almacenado correctamente el objeto Usuario en Session";
                }else if(btnpulsado.Value == 2)
                {
                    //RECUPERAMOS EL OBJETO USUARIO ALMANCENADO EN SESSION
                    Usuario user = HttpContext.Session.GetObject<Usuario>("usuario");
                    ViewData["usuario"] = user;
                }
            }
            return View();
        }
    }
}

GuardarSessionObjetos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuardarSessionObjetos/Views/Session/GuardarObjetoSession.cshtml
@{
    Usuario user = ViewData["usuario"] as Usuario;
}

<h1 class="text-primary text-center">
    Almacenando y mostrando el Objeto Usuario
</h1>
<br />
<div class="d-flex gap-4 justify-content-center align-items-center">
    <a asp-controller="Session" asp-action="GuardarObjetoSession"
        asp-route-btnpulsado="1" class="btn btn-primary p-3">
        Almacenar Usuario
    </a>
    <a asp-controller="Session" asp-action="GuardarObjetoSession"
       asp-route-btnpulsado="2" class="btn btn-success p-3">
        Mostrar Usuario
    </a>
</div>
<br />
<h2 class="text-secondary text-center">
    @ViewData["mensaje"]
</h2>

@if(user != null)
{
    <h2>Usuario Almacenado</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Email</th>
                <th>Edad</th>
                <th>Ciudad</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@user.Nombre</td>
                <td>@user.Email</td>
                <td>@user.Edad</td>
                <td>@user.Ciudad</td>
            </tr>
        </tbody>
    </table>
}

GuardarSessionObjetos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuardarSessionObjetos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GuardarSessionObjetos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuardarSessionObjetos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Session" asp-action="GuardarObjetoSession">
                                Guardar Objeto Session
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GuardarSessionObjetos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>